astropix2:
  geometry:
    cols: 35
    rows: 35
  config:
    digitalconfig:
      interrupt_pushpull:
      - 1
      - 1
      en_inj:
      - 19
      - 0
      reset:
      - 1
      - 0
      extrabits:
      - 14
      - 0
    biasconfig:
      DisHiDR:
      - 1
      - 0
      q01:
      - 1
      - 0
      qon0:
      - 1
      - 0
      qon1:
      - 1
      - 1
      qon2:
      - 1
      - 0
      qon3:
      - 1
      - 1
    idacs:
      blres:
      - 6
      - 0
      nu1:
      - 6
      - 0
      vn1:
      - 6
      - 20
      vnfb:
      - 6
      - 3
      vnfoll:
      - 6
      - 10
      nu5:
      - 6
      - 0
      nu6:
      - 6
      - 0
      nu7:
      - 6
      - 0
      nu8:
      - 6
      - 0
      vn2:
      - 6
      - 0
      vnfoll2:
      - 6
      - 4
      vnbias:
      - 6
      - 0
      vpload:
      - 6
      - 5
      nu13:
      - 6
      - 0
      vncomp:
      - 6
      - 2
      vpfoll:
      - 6
      - 60
      nu16:
      - 6
      - 0
      vprec:
      - 6
      - 15
      vnrec:
      - 6
      - 2
    recconfig:
      col0:
      - 38
      - 137447342656
      col1:
      - 38
      - 536870912
      col2:
      - 38
      - 2162816
      col3:
      - 38
      - 117448704
      col4:
      - 38
      - 4272
      col5:
      - 38
      - 33554944
      col6:
      - 38
      - 4429709312
      col7:
      - 38
      - 8454146
      col8:
      - 38
      - 2281832512
      col9:
      - 38
      - 4194336
      col10:
      - 38
      - 4294971392
      col11:
      - 38
      - 512
      col12:
      - 38
      - 8388816
      col13:
      - 38
      - 33554432
      col14:
      - 38
      - 570449920
      col15:
      - 38
      - 19327418368
      col16:
      - 38
      - 536936576
      col17:
      - 38
      - 4429185024
      col18:
      - 38
      - 552
      col19:
      - 38
      - 32768
      col20:
      - 38
      - 2097188
      col21:
      - 38
      - 17716871172
      col22:
      - 38
      - 256
      col23:
      - 38
      - 1179648
      col24:
      - 38
      - 16793600
      col25:
      - 38
      - 134382592
      col26:
      - 38
      - 67115840
      col27:
      - 38
      - 67141640
      col28:
      - 38
      - 8589934756
      col29:
      - 38
      - 38658916352
      col30:
      - 38
      - 1073807360
      col31:
      - 38
      - 5370806280
      col32:
      - 38
      - 8388616
      col33:
      - 38
      - 17179869184
      col34:
      - 38
      - 0
