astropix2:
  geometry:
    cols: 35
    rows: 35
  config:
    digitalconfig:
      interrupt_pushpull:
      - 1
      - 1
      en_inj:
      - 19
      - 0
      reset:
      - 1
      - 0
      extrabits:
      - 14
      - 0
    biasconfig:
      DisHiDR:
      - 1
      - 0
      q01:
      - 1
      - 0
      qon0:
      - 1
      - 0
      qon1:
      - 1
      - 1
      qon2:
      - 1
      - 0
      qon3:
      - 1
      - 1
    idacs:
      blres:
      - 6
      - 0
      nu1:
      - 6
      - 0
      vn1:
      - 6
      - 20
      vnfb:
      - 6
      - 3
      vnfoll:
      - 6
      - 10
      nu5:
      - 6
      - 0
      nu6:
      - 6
      - 0
      nu7:
      - 6
      - 0
      nu8:
      - 6
      - 0
      vn2:
      - 6
      - 0
      vnfoll2:
      - 6
      - 4
      vnbias:
      - 6
      - 0
      vpload:
      - 6
      - 5
      nu13:
      - 6
      - 0
      vncomp:
      - 6
      - 2
      vpfoll:
      - 6
      - 60
      nu16:
      - 6
      - 0
      vprec:
      - 6
      - 15
      vnrec:
      - 6
      - 2
    recconfig:
      col0:
      - 38
      - 206150041022
      col1:
      - 38
      - 68182605822
      col2:
      - 38
      - 68717313918
      col3:
      - 38
      - 68602028030
      col4:
      - 38
      - 68719472462
      col5:
      - 38
      - 68685921790
      col6:
      - 38
      - 64289767422
      col7:
      - 38
      - 68711022588
      col8:
      - 38
      - 66437644222
      col9:
      - 38
      - 68715282398
      col10:
      - 38
      - 64424505342
      col11:
      - 38
      - 68719476222
      col12:
      - 38
      - 68711087918
      col13:
      - 38
      - 68685922302
      col14:
      - 38
      - 68149026814
      col15:
      - 38
      - 49392058366
      col16:
      - 38
      - 68182540158
      col17:
      - 38
      - 64290291710
      col18:
      - 38
      - 68719476182
      col19:
      - 38
      - 68719443966
      col20:
      - 38
      - 68717379546
      col21:
      - 38
      - 51002605562
      col22:
      - 38
      - 68719476478
      col23:
      - 38
      - 68718297086
      col24:
      - 38
      - 68702683134
      col25:
      - 38
      - 68585094142
      col26:
      - 38
      - 68652360894
      col27:
      - 38
      - 68652335094
      col28:
      - 38
      - 60129541978
      col29:
      - 38
      - 30060560382
      col30:
      - 38
      - 67645669374
      col31:
      - 38
      - 63348670454
      col32:
      - 38
      - 68711088118
      col33:
      - 38
      - 51539607550
      col34:
      - 38
      - 68719476734
